# Generated by Django 4.0.2 on 2022-04-10 15:14

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_link_project_github_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="body",
            field=markdownx.models.MarkdownxField(
                help_text="For accessibility use h2 tags for subheadings."
            ),
        ),
    ]
