# Generated by Django 4.0.2 on 2022-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="short_bio",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
