# Generated by Django 4.0.2 on 2022-03-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_short_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="social_github",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="social_linkedin",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
