# Generated by Django 4.0.2 on 2022-03-15 17:28

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_social_github_customuser_social_linkedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="social_image",
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
