# Generated by Django 4.0.2 on 2022-02-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="published",
            new_name="is_published",
        ),
    ]
